src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $start_session = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $end_session = null;

    #[ORM\Column]
    private ?int $nb_places = null;

    #[ORM\Column]
    private ?int $nb_places_reserved = null;

    /**
     * @var Collection<int, Trainee>
     */
    #[ORM\ManyToMany(targetEntity: Trainee::class, mappedBy: 'sessions')]
    private Collection $trainees;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session',  cascade: ['persist'], orphanRemoval: true)]
    private Collection $programmes;

    public function __construct()
    {
        $this->trainees = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartSession(): ?\DateTimeImmutable
    {
        return $this->start_session;
    }

    public function setStartSession(\DateTimeImmutable $start_session): static
    {
        $this->start_session = $start_session;

        return $this;
    }

    public function getEndSession(): ?\DateTimeImmutable
    {
        return $this->end_session;
    }

    public function setEndSession(\DateTimeImmutable $end_session): static
    {
        $this->end_session = $end_session;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): static
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    public function getNbPlacesReserved(): ?int
    {
        return $this->nb_places_reserved;
    }

    public function setNbPlacesReserved(int $nb_places_reserved): static
    {
        $this->nb_places_reserved = $nb_places_reserved;

        return $this;
    }

    /**
     * @return Collection<int, Trainee>
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): static
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees->add($trainee);
            $trainee->addSession($this);
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): static
    {
        if ($this->trainees->removeElement($trainee)) {
            $trainee->removeSession($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
    
}

src/Entity/Trainee.php
<?php

namespace App\Entity;

use App\Repository\TraineeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: TraineeRepository::class)]
class Trainee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $first_name = null;

    #[ORM\Column(length: 5)]
    private ?string $sex = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_birth = null;

    #[ORM\Column(length: 100)]
    private ?string $town = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $telephone = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\ManyToMany(targetEntity: Session::class, inversedBy: 'trainees')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->date_birth = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): static
    {
        $this->sex = $sex;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeImmutable
    {
        return $this->date_birth;
    }

    public function setDateBirth(\DateTimeImmutable $date_birth): static
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): static
    {
        $this->town = $town;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        $this->sessions->removeElement($session);

        return $this;
    }

    public function getAge(): ?string {

        $now = new \DateTime();
        $interval = $this->date_birth->diff($now);
        return $interval->format('%y');

    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Controller/TraineeController.php
<?php

namespace App\Controller;

use App\Entity\Trainee;
use App\Form\TraineeType;
use App\Repository\TraineeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TraineeController extends AbstractController
{
    // Route pour afficher la liste des stagiaires
    #[Route('/trainee', name: 'trainee')]
    
    public function index(
        
        TraineeRepository $repository,
        PaginatorInterface $paginator,
        Request $request
        
    ): Response {

        $trainees = $paginator->paginate(
            // Récupération de tous les stagiaires à partir du repository
            $trainees = $repository->findAll(),
            $request->query->getInt('page', 1), 
            10
        );

        

        // Rendu du template Twig en passant la liste des stagiaires
        return $this->render('/pages/trainee/index.html.twig', [
            'trainees' => $trainees,
        ]);
    }

    #[Route('/trainee/new', name: 'trainee.new', methods: ['GET', 'POST'])]
    public function newTrainee(
        
        Request $request,
        EntityManagerInterface $entityManager
        
        ): Response {

            $trainee = new Trainee();

            $form = $this->createForm(TraineeType::class, $trainee);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $trainee = $form->getData();
                $entityManager->persist($trainee);
                $entityManager->flush();

                return $this->redirectToRoute('trainee');
            }   

        return $this->render('/pages/trainee/new.html.twig', [
                'formAddTrainee' => $form,
        ]);
    }

    #[Route('/trainee/edition/{id}', name: 'trainee.edit', methods: ['GET', 'POST'])]
    public function editTrainee(
        
        int $id, 
        TraineeRepository $repository,  
        Request $request, 
        EntityManagerInterface $manager
        
        ): Response {
        $trainee = $repository->find($id);
        if (!$trainee) {
            throw $this->createNotFoundException('Stagiaire non trouvé');
        }

        $form = $this->createForm(traineeType::class, $trainee);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $trainee = $form->getData();

            $manager->persist($trainee);

            $manager->flush();

            $this->addFlash(
                'success',
                'La modification à été faite avec succès de ' . $trainee->getName() . ' ' . $trainee->getFirstName()
            );
            return $this->redirectToRoute('trainee');
        }
        return $this->render('pages/trainee/edit.html.twig', [
            'formAddTrainee' => $form->createView(),
        ]);
    }

    // Route pour afficher les détails d'une session spécifique identifiée par son 'id'
    #[Route('/trainee/{id}', name: 'show_trainee')]
    public function showTrainee(
        
        TraineeRepository $repository, 
        ?Trainee $trainee,
        
        ): Response {

        // j'utilise ici une méthode personnalisée 'findProgramsBySession' qui récupère la session et ses relations (programmes)
        $trainee = $repository->findSessionsByTrainee($trainee);

        // Vérification si la session a bien été trouvée
        if (!$trainee) {
            throw $this->createNotFoundException('Le stagiaire demandée n\'existe pas.');
        }

        // On passe la session récupérée à la vue via le tableau associatif 'session'
        return $this->render('/pages/trainee/show.html.twig', [
            'trainee' => $trainee
        ]);
    }


    #[Route('/trainee/suppression/{id}', name: 'trainee.delete', methods: ['GET', 'POST'])]
    public function deleteTrainee(
        
        int $id, 
        TraineeRepository $repository, 
        EntityManagerInterface $manager,
        
        ): Response {
    
        // Recherche du trainee avec l'ID fourni
        $trainee = $repository->find($id);
    
        // Vérification si le trainee existe
        if ($trainee) {
            // Si le trainee est trouvé, suppression
            $manager->remove($trainee);
            $manager->flush();

            $this->addFlash(
                'success',
                'La suppression du stagiaire à été faite avec succès  : ' . $trainee->getName()
                
            );
        } else {
            $this->addFlash(
                'warning',
                'Echec lors de la suppression du stagiaire.'
            );
        }
    
        // Redirection vers la route 'trainee'
        return $this->redirectToRoute('trainee');
    }
}

templates/pages/trainee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modifier un stagiaire {% endblock %}

{% block body %}

<div class="container mt-3">

   <h1 class="mt-4 mb-4"> Modifier un stagiaire </h1>

   {{ form_start(formAddTrainee) }}
   
        <div class="row">
            <div class="col-sm">
                {{form_row(formAddTrainee.name)}}
            </div>
            <div class="col-sm">
                {{form_row(formAddTrainee.first_name)}}
            </div>
        </div>

        <div class="row">
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.sex)}}
            </div>
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.date_birth)}}
            </div>
        </div>

        <div class="row">
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.town)}}
            </div>
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.telephone)}}
            </div>
        </div>

        <div class="row mt-4">
      
        {{form_row(formAddTrainee.email)}}

        </div>
      
   {{ form_end(formAddTrainee) }}

    <a href="{{ path('trainee') }}"> <button type="submit" class="btn btn-dark mb-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour </button> </a>
 
</div>

{% endblock %}

templates/pages/trainee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les stagiaires{% endblock %}

{% block body %}

<div class="container mt-4 mb-4">

    <h1>Les stagiaires</h1>

        {% for message in app.flashes('success') %}

        <div class="flash-message flash-success">
            <span class="icon">✔️</span> {{ message}}
        </div>

        {% endfor %}

        {% for message in app.flashes('warning') %}

        <div class="flash-message flash-warning">
            <span class="icon">⚠️</span> {{ message }}
        </div>

        {% endfor %}

    <table class="table table-dark mt-4 mb-4">
        <thead>
            <tr>
                <th scope="col" class="center size text-uppercase">Nom       </th>
                <th scope="col" class="center size text-uppercase">Prénom    </th>
                {% if app.user %}
                <th scope="col" class="center size text-uppercase">Sexe      </th>
                <th scope="col" class="center size text-uppercase">Date      </th>
                <th scope="col" class="center size text-uppercase">Ville     </th>
                <th scope="col" class="center size text-uppercase">Email     </th>
                <th scope="col" class="center size text-uppercase">Téléphone </th>
                {% else %}

                {% endif %}
                <th scope="col" class="center size text-uppercase">Détails   </th>
            </tr>
        </thead>
        <tbody>
            {% for trainee in trainees %}
                <tr class="table-primary">
                    <td class="center"> {{ trainee.name }}                         </td>
                    <td class="center"> {{ trainee.firstName }}                    </td>
                    {% if app.user %}
                    <td class="center"> {{ trainee.sex }}                          </td>
                    <td class="center"> {{ trainee.dateBirth|date('d/m/Y')  }}     </td>
                    <td class="center"> {{ trainee.town }}                         </td>
                    <td class="center"> {{ trainee.email }}                        </td>
                    <td class="center"> {{ trainee.telephone }}                    </td>
                    {% else %}

                    {% endif %}
                    <td class="center"> <a href="{{ path('show_trainee',{id:trainee.id}) }}"> <img class="icone" src="{{ asset('img/detail.jpg') }}" title="Détails du stagiaire" alt="Détails du stagiaire"/></a></td> 
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="navigation mt-3 mb-3">
        {{ knp_pagination_render(trainees) }}
    </div>
    
    {% if app.user %}
        <a href="{{ path('trainee.new') }}"> <button type="button" class="btn btn-dark mb-4"> Ajouter un stagiaire </button> </a>
    {% else %}

    {% endif %}
</div>

{% endblock %}

templates/pages/trainee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un stagiaire{% endblock %}

{% block body %}

<div class="container mt-4">

   <h1>Ajouter un stagiaire</h1>

   {{ form_start(formAddTrainee) }}
   
        <div class="row">
            <div class="col-sm">
                {{form_row(formAddTrainee.name)}}
            </div>
            <div class="col-sm">
                {{form_row(formAddTrainee.first_name)}}
            </div>
        </div>

        <div class="row">
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.sex)}}
            </div>
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.date_birth)}}
            </div>
        </div>

        <div class="row">
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.town)}}
            </div>
            <div class="col-sm  mt-4">
                {{form_row(formAddTrainee.telephone)}}
            </div>
        </div>

        <div class="row mt-4">
      
        {{form_row(formAddTrainee.email)}}

        </div>
      
   {{ form_end(formAddTrainee) }}

   <a href="{{ path('trainee') }}"> <button type="submit" class="btn btn-dark mt-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour </button> </a>
 
</div>
{% endblock %}

templates/pages/trainee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Fiche stagiaires {% endblock %}

{% block body %}

<div class="container mt-4">
    
    <h1>  <img src="{{ asset('img/contact.png') }}" alt="logo" srcset=""> Fiche stagiaires</h1>

        <h2 class="mb-4"> <b> {{ trainee.firstName }} {{ trainee.name }}  </b> </h2>

            <div>
                {% if app.user %}
                <p> <b> Sexe : </b> {{ trainee.sex }} </p> 
                <p> <b> Date de naissance : </b> {{ trainee.dateBirth|date('d/m/Y') }} ({{trainee.age}} ans)</p> 
                <p> <b> Ville : </b> {{ trainee.town }}  </p>
                <p> <b> Courriel : </b> {{ trainee.email }} </p>
                <p> <b> Téléphone : </b> {{ trainee.telephone }} </p>
                {% else %}

                {% endif %}

            </div>

        <h3 class="mt-4 mb-4"> Sessions  prévues </h3>

            <div class="mt-3 mb-4">

                {% for session in trainee.sessions %}

                <tr>
                    <td>
                        <ul> 
                            <li> 
                                <p>
                                    
                                    <b><a class="text-decoration-none " title="Lien vers la session" href="{{path('show_session', {id:session.id}) }}"> {{ session.name }} </a></b>

                                    (Du {{ session.startSession|date('d/m/Y') }} au {{ session.endSession|date('d/m/Y')   }})
                                </p>
                            </li>
                        </ul>
                    </td>
                </tr>

                {% endfor %}

            </div>

            {% if app.user %}

            <div style="display: flex; gap: 20px;">
                <td> <a href="{{ path('trainee.edit',   {id:trainee.id}) }}"><button type="button" class="btn btn-warning" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Modifier le stagiaire  </button></a>
                <td> <a href="{{ path('trainee.delete', {id:trainee.id}) }}"><button type="button" class="btn btn-danger " data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Supprimer le stagaire </button></a>
            </div>

            {% else %}

            {% endif %}


    <a href="{{ path('trainee') }}"> <button type="submit" class="btn btn-dark mt-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour </button> </a>
    

</div>

{% endblock %}