src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $start_session = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $end_session = null;

    #[ORM\Column]
    private ?int $nb_places = null;

    #[ORM\Column]
    private ?int $nb_places_reserved = null;

    /**
     * @var Collection<int, Trainee>
     */
    #[ORM\ManyToMany(targetEntity: Trainee::class, mappedBy: 'sessions')]
    private Collection $trainees;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session',  cascade: ['persist'], orphanRemoval: true)]
    private Collection $programmes;

    public function __construct()
    {
        $this->trainees = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartSession(): ?\DateTimeImmutable
    {
        return $this->start_session;
    }

    public function setStartSession(\DateTimeImmutable $start_session): static
    {
        $this->start_session = $start_session;

        return $this;
    }

    public function getEndSession(): ?\DateTimeImmutable
    {
        return $this->end_session;
    }

    public function setEndSession(\DateTimeImmutable $end_session): static
    {
        $this->end_session = $end_session;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): static
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    public function getNbPlacesReserved(): ?int
    {
        return $this->nb_places_reserved;
    }

    public function setNbPlacesReserved(int $nb_places_reserved): static
    {
        $this->nb_places_reserved = $nb_places_reserved;

        return $this;
    }

    /**
     * @return Collection<int, Trainee>
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): static
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees->add($trainee);
            $trainee->addSession($this);
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): static
    {
        if ($this->trainees->removeElement($trainee)) {
            $trainee->removeSession($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
    
}

src/Entity/Trainee.php
<?php

namespace App\Entity;

use App\Repository\TraineeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: TraineeRepository::class)]
class Trainee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $first_name = null;

    #[ORM\Column(length: 5)]
    private ?string $sex = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_birth = null;

    #[ORM\Column(length: 100)]
    private ?string $town = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $telephone = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\ManyToMany(targetEntity: Session::class, inversedBy: 'trainees')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->date_birth = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): static
    {
        $this->sex = $sex;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeImmutable
    {
        return $this->date_birth;
    }

    public function setDateBirth(\DateTimeImmutable $date_birth): static
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): static
    {
        $this->town = $town;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        $this->sessions->removeElement($session);

        return $this;
    }

    public function getAge(): ?string {

        $now = new \DateTime();
        $interval = $this->date_birth->diff($now);
        return $interval->format('%y');

    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Trainee;
use App\Form\SessionType;
use App\Repository\SessionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SessionController extends AbstractController
{
    // Le chemin est '/session' et le nom de la route est 'session'
    #[Route('/session', name: 'session')]
    
    public function index(
        
        SessionRepository $repository,
        PaginatorInterface $paginator,
        Request $request
        
    ): Response{

        $sessions = $paginator->paginate(
            $sessions = $repository->findAll(),
            $request->query->getInt('page', 1), 
            10
        );

        // On passe les sessions récupérées à la vue via le tableau associatif 'sessions'
        return $this->render('/pages/session/index.html.twig', [
            'sessions' => $sessions
        ]);
    }

    #[Route('/session/new', name: 'session.new', methods: ['GET', 'POST'])]

    public function newSession(
        
        Request $request,
        EntityManagerInterface $entityManager
        
    ): Response {

        $session = new Session();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $session = $form->getData();
            $entityManager->persist($session);
            $entityManager->flush();

            return $this->redirectToRoute('session');
        }   

        return $this->render('/pages/session/new.html.twig', [
            'form' => $form,
            'sessionId'=> $session->getId()
        ]);
    }

    #[Route('/session/edition/{id}', name: 'session.edit', methods: ['GET', 'POST'])]
    public function editSession(
        
        int $id, 
        SessionRepository $repository,  
        Request $request, 
        EntityManagerInterface $manager
        
        ): Response {
        $session = $repository->find($id);

        if (!$session) {
            throw $this->createNotFoundException('Session non trouvé');
        }

        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        // dd($session);
        if ($form->isSubmitted() && $form->isValid()) {

            $session = $form->getData();

            $manager->persist($session);
            $manager->flush();

            $this->addFlash(
                'success',
                'La modification à été faite avec succès de '
            );
            return $this->redirectToRoute('show_session', ['id' => $session->getId()]);

        }
        return $this->render('pages/session/edit.html.twig', [
            'form' => $form->createView(),
            'sessionId'=> $session->getId()
        ]);
    }
  

    // Route pour afficher les détails d'une session spécifique identifiée par son 'id'
    #[Route('/session/{id}', name: 'show_session')]
    public function showSession(
        
        SessionRepository $repository, 
        ?Session $session = null,
        
        ): Response {

            if (!$session instanceof Session) {
                throw $this->createNotFoundException('La session demandée n\'existe pas.');
            }
            
            $programmes = $session->getProgrammes();
            $traineesNotInSession = $session->getTrainees();

      
            
            if (!empty($programmes)) {
                // On garde la session inchangée et on récupère les programmes associés
                $programmes = $repository->findProgramsBySession($session);
            }

            $traineesNotInSession = $repository->listTraineesNotInSession($session);
            $nombreDePlacesReservees = count($session->getTrainees());


        // On passe la session récupérée à la vue via le tableau associatif 'session'
        return $this->render('/pages/session/show.html.twig', [
            'session' => $session,
            'trainees' => $traineesNotInSession,
            'nombreDePlacesReservees' => $nombreDePlacesReservees
        ]);
    }

    // Route pour supprimer une session spécifique identifiée par son 'id'
    #[Route('/session/unsubscribe/{session}/{trainee}', name: 'session.unsubscribe', methods: ['GET', 'POST'])]
    public function unsubscribeTraineeInSession(
        
        Session $session,
        Trainee $trainee,
        EntityManagerInterface $manager

        ): Response {

            $session->removeTrainee($trainee);
            $trainee->removeSession($session);

            $manager->persist($trainee);
            $manager->persist($session);
            $manager->flush();
    
        // Redirection vers la route 'session'
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }


    // Route pour supprimer une session spécifique identifiée par son 'id'
    #[Route('/session/subscribe/{session}/{trainee}', name: 'session.subscribe', methods: ['GET', 'POST'])]
    public function subscribeTraineeInSession(
        
        Session $session,
        Trainee $trainee,
        EntityManagerInterface $manager

        ): Response {

            $session->addTrainee($trainee);
            $trainee->addSession($session);

            $manager->persist($trainee);
            $manager->persist($session);
            $manager->flush();
    
        // Redirection vers la route 'session'
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }


    // Route pour supprimer une session spécifique identifiée par son 'id'
    #[Route('/session/suppression/{id}', name: 'session.delete', methods: ['GET', 'POST'])]

    public function deleteSession(
        
        int $id, 
        SessionRepository $repository, 
        EntityManagerInterface $manager,
        
        ): Response {
    
        // Recherche de la session avec l'ID fourni
        $session = $repository->find($id);
    
        // Vérification si la session existe
        if ($session) {
            // Si la session est trouvée, suppression
            $manager->remove($session);
            $manager->flush();
    
            $this->addFlash(
                'success',
                'Suppression avec succès de la session : ' . $session->getName()
            );
        } else {
            $this->addFlash(
                'warning',
                'Echec lors de la suppression de la session.'
            );
        }
    
        // Redirection vers la route 'session'
        return $this->redirectToRoute('session');
    }

    

}

templates/pages/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une session{% endblock %}

{% block body %}

<div class="container">

<h1>Modifier une session</h1>

{{ form_start(form) }}

{{form_row(form.name)}}
{{form_row(form.start_session)}}
{{form_row(form.end_session)}}
{{form_row(form.nb_places)}}
{{form_row(form.nb_places_reserved)}}

<h2>Programme de la session</h2>

<div class="form-group row">
    {# <div class="col-form-label col-sm-2">$nbsp;</div> #}
    <div id="programme-fields-list" class="col-sm-10 remove-collection-widget"
    data-prototype="{{ form_widget(form.programmes.vars.prototype)|e }}"
    data-session="{{sessionId}}"
    data-widget-tags="{{'<p></p>'|e}}"
    data-widget-counter="{{ form.programmes|length }}">
{% for programmeField in form.programmes %}
    <p>
        {{ form_errors(programmeField) }}
        {{ form_widget(programmeField, {'attr': {'class': 'borders'}}) }}
    </p>
{% endfor %}
</div>
</div>
<div class="form-group row flex-action">
<button type="button" 
class="add-another-collection-widget button"
data-list-selector="#programme-fields-list">Ajouter un nouveau programme</button>
</div>


{{ form_end(form) }}


<a href="{{ path('session') }}"> <button type="submit" class="btn btn-dark mt-4 mb-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour</button> </a>

</div>

{% endblock %}

templates/pages/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les sessions{% endblock %}

{% block body %}

<div class="container mt-4">

<h1>Les sessions</h1>

{% for message in app.flashes('success') %}

<div class="flash-message flash-success">
    <span class="icon">✔️</span> {{ message}}
</div>

{% endfor %}

{% for message in app.flashes('warning') %}

<div class="flash-message flash-warning">
    <span class="icon">⚠️</span> {{ message }}
</div>

{% endfor %}

<table class="table table-dark mt-4 mb-4">
    <thead>
        <tr>
            <th scope="col" class="center size text-uppercase"> Nom</th>
            <th scope="col" class="center size text-uppercase"> Début de session</th>
            <th scope="col" class="center size text-uppercase"> Fin de session</th>
            <th scope="col" class="center size text-uppercase"> N° de places théoriques</th>
            <th scope="col" class="center size text-uppercase"> N° places réservées</th>
            <th scope="col" class="center size text-uppercase"> N° de places restantes</th>
            <th scope="col" class="center size text-uppercase"> Détails</th>
        </tr>
    </thead>
    <tbody>
        {% for session in sessions %}
            <tr class="table-primary">
                <td class="center">{{ session.name }}</td>
                <td class="center">{{ session.startSession|date('d/m/Y') }}</td>
                <td class="center">{{ session.endSession|date('d/m/Y') }}</td>
                <td class="center">{{ session.nbPlaces }}</td>
                <td class="center">{{ session.nbPlacesReserved }}</td>
                <td class="center">{{ session.nbPlaces - session.nbPlacesReserved }}</td>
                <td class="center"> <a href="{{ path('show_session', {id:session.id}) }}"> <img class="icone" src="{{ asset('img/detail.jpg') }}" title="Détails de la session" alt="Détails de la session"/></a></td> 
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="navigation mt-3 mb-3">
    {{ knp_pagination_render(sessions) }}
</div>

    {% if app.user %}
        <a href="{{ path('session.new') }}"> <button type="button" class="btn btn-dark mb-4"> Ajouter une session </button> </a>
    {% else %}
    {% endif %}
</div>
{% endblock %}

templates/pages/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une sessions{% endblock %}

{% block body %}

<div class="container">

<h1>Ajouter une session</h1>

<div class="test">
    {{ form_start(form) }}
    
        {{form_row(form.name)}}
        {{form_row(form.start_session)}}
        {{form_row(form.end_session)}}
        {{form_row(form.nb_places)}}
        {{form_row(form.nb_places_reserved)}}
        
        <h2 class="mt-4">Programme de la session</h2>
    
        <div class="form-group row mt-3">
            <div id="programme-fields-list" class="col-sm-10 remove-collection-widget"
            data-prototype="{{ form_widget(form.programmes.vars.prototype)|e }}"
            data-session="{{sessionId}}"
            data-widget-tags="{{'<p></p>'|e}}"
            data-widget-counter="{{ form.programmes|length }}">
        {% for programmeField in form.programmes %}
            <p>
                {{ form_errors(programmeField) }}
                {{ form_widget(programmeField, {'attr': {'class': 'borders'}}) }}
            </p>
        {% endfor %}
        </div>
    </div>
    <div class="form-group row flex-action">
        <button type="button" 
        class="add-another-collection-widget button"
        data-list-selector="#programme-fields-list">Ajout d'un programme</button>
    </div>
    
    
    {{ form_end(form) }}
</div>



<a href="{{ path('session') }}"> <button type="submit" class="btn btn-dark mt-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour</button> </a>

</div>

{% endblock %}

templates/pages/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une sessions{% endblock %}

{% block body %}

<div class="container mt-4">

    <div class="table-container">

        <h1>Détail de la session </h1>
    
        <div class="container-information">
            <p><b class=" size font-weight-bold">Name :</b> {{ session.name }}</p>
            <p><b class=" size font-weight-bold">Date de démarrage :</b> {{ session.startSession|date('d/m/Y') }}</p>
            <p><b class=" size font-weight-bold">Date de fin :</b> {{ session.endSession|date('d/m/Y') }}</p>
            <p><b class=" size font-weight-bold">Nombre de places total :</b> {{ session.nbPlaces }}</p>
            <p><b class=" size font-weight-bold">Nombre de places réservées :</b> {{  nombreDePlacesReservees }}</p>
            {% set placesRestantes = session.nbPlaces - nombreDePlacesReservees %}
            <p ><b class=" size font-weight-bold">Nombre de places restantes :</b> {{ placesRestantes }}</p>
            {% if placesRestantes < 0 %}
                <p class="bg-warning pt-5 pb-5 center " style="color: red; font-size:large"><b>VOUS AVEZ DÉPASSÉ LE NOMBRE DE STAGIAIRES PRÉVU POUR CETTE SESSION</b></p>
            {% endif %}
                </div>

        </div>

    <div class="container mt-3">

        <h2> Les stagiaires </h2>
        
        <div class="table-container" style="display: flex; gap:20px;">

            <table class="table table-dark mt-4 mb-4 center">
                <thead>
                    <tr>
                        <th>Stagiaire inscrit</th>
                        {% if app.user %}
                        <th></th>
                        {% else %}

                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for trainee in session.trainees %}
                    <tr class="table-primary">
                        <td >{{ trainee.name }} {{ trainee.firstName }}</td>
                        {% if app.user %}
                        <td><a href="{{ path('session.unsubscribe', { session:session.id, trainee:trainee.id }) }}"><button type="button" class="btn btn-danger" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Désinscrive de l'élève </button> </a> </td>
                        {% else %}

                        {% endif %}
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
            
            <table class="table table-dark mt-4 mb-4 center ">
                <thead>
                    <tr>
                        <th>Stagiaire Non inscrit</th>
                        {% if app.user %}
                        <th></th>
                        {% else %}

                        {% endif %}
                    <tr>
                </thead>
                <tbody>
                    {% for trainee in trainees %}
                        <tr class="table-primary">
                            <td>{{ trainee.name }} {{ trainee.firstName }}</a></td>
                            {% if app.user %}
                            <td><a href="{{ path('session.subscribe',{ session:session.id, trainee:trainee.id }) }}"><button type="button" class="btn btn-success" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Inscrire le stagiaire </button> </a> </td>
                            {% else %}

                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h2 class="mt-2"> Le Programme </h2>
        
        <table class="table table-dark mt-4 mb-4 center" >
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Début de session</th>
                </tr>
            </thead>
            <tbody>
                {% if session.programmes | default %}
                    {% for program in session.programmes %}
                        <tr class="table-primary">
                            <td>{{ program.unit.name }} </td>
                            <td>{{ program.nbdays }} jours </td>
                        </tr>
                    {% endfor %}
                {% endif %}

            </tbody>
        </table>

    {% if app.user %}
            <div style="display: flex; gap: 20px;">
                <a href="{{ path('session.edit',   {id:session.id}) }}"><button type="button" class="btn btn-warning" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Modifier la session  </button></a>
                <a href="{{ path('session.delete', {id:session.id}) }}"><button type="button" class="btn btn-danger " data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Supprimer la session </button></a>
            </div>
        {% else %}

        {% endif %}

        <div class="mt-5">
            <a href="{{ path('session') }}"> <button type="submit" class="btn btn-dark mb-4" data-nlok-ref-guid="1758b875-4f72-41d6-f4d6-49b1b6ef4bd5"> Retour </button> </a>
        </div>

    </div>
    

</div>

{% endblock %}